apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mortgage-platform/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-url
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auth0-domain
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auth0-client-id
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auth0-client-secret
        - name: LANTMATERIET_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: lantmateriet-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL21vcnRnYWdlX2Ri
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  auth0-domain: eW91ci1hdXRoMC1kb21haW4uYXV0aDAuY29t
  auth0-client-id: eW91ci1hdXRoMC1jbGllbnQtaWQ=
  auth0-client-secret: eW91ci1hdXRoMC1jbGllbnQtc2VjcmV0
  lantmateriet-api-key: eW91ci1sYW50bWF0ZXJpZXQtYXBpLWtleQ==
